### ISSUE TITLE
Typo in skipnet/imagenet/models.py

### ISSUE THREAD

**Issue by jgong5** [ucbdrive/skipnet#1]
line 402: mask, grob = self.control(gate_feature)
"grob" should be "gprob" instead. Will this impact the claims from the paper?

**Comment by xinw1012** [comment]
Thanks for pointing out the typo.  The variable name used in the original code for the paper was "gprob" and the typo occurred when I cleaned up the code for the release.  We are working on another release which will have better documentation and trained model checkpoints.  Keep tuned!
