### ISSUE TITLE
cifar10 rl training

### ISSUE THREAD

**Issue by eleanor11** [ucbdrive/skipnet#2]
Hi,

I have met a problem on cifar10 training.
It is that when training feedforward_rl_38 and rnn_gate_rl_38, it goes wrong in line 230 with the error 'RuntimeError: differentiating stochastic functions requires providing a reward'. Do you have any idea on this issue?

Thank you

**Comment by xinw1012** [comment]
Hi,  please pull again.  I accidentally commented out line 227-228 and missed a flag when setting the gate actions.  You should be able to run it now.  Also, set `--gate-type` to `ff` when you run feedforward model and `rnn` for recurrent gate models. I also updated the readme file for that. Thanks for pointing this out. Let me know if there is any more issue training this.
