### ISSUE TITLE
Typo in forward of ResNetRecurrentGateSP

### ISSUE THREAD

**Issue by volcacius** [ucbdrive/skipnet#4]
There is a typo in the forward method of ResNetRecurrentGateSP (could be elsewhere as well, haven't checked) under CIFAR, _grob_ instead of _gprob_. Wrong values are returned up to the top function of the training loop, but thankfully they are not used.

```python
 for g in range(3):
            for i in range(0 + int(g == 0), self.num_layers[g]):
                ...
                mask, grob = self.control(gate_feature)
                gprobs.append(gprob)
                ...
```

**Comment by xinw1012** [comment]
Thanks for pointing that out! I will update the code accordingly.

Best,
Xin
